name: "🚀 Feature Request"
description: "Suggest a new idea or enhancement for Scryarc."
title: "[Feature] A brief, clear summary of the new feature"
labels: ["enhancement", "status: triage"]
type: "Feature"
projects: ["GalacticCampaigns/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to Scryarc! Your ideas are valuable for making the bot better for everyone. Please fill out the following sections to help us understand your vision.

  - type: textarea
    id: problem-statement
    attributes:
      label: "Is your feature request related to a problem?"
      description: "A clear and concise description of what the problem is. Ex. 'As a server admin, I find it difficult when...'"
      placeholder: "I find it difficult to get a quick overview of all the active games on my server without scrolling through many channels."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen. If you're suggesting a new command, describe its name, options, and what it should do."
      placeholder: "I would like a new command, maybe `/list_games`, that shows a paginated embed of all active games, who the GM is, and a link to the channel."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "An alternative would be to add this to the `/config view` command, but that command is already very long."

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context, mockups, or screenshots about the feature request here."

  - type: checkboxes
    id: final-check
    attributes:
      label: "Final Checklist"
      description: "Please confirm you've completed the following."
      options:
        - label: "I have searched the [existing issues](https://github.com/GalacticCampaigns/scryarc/issues) to make sure this feature has not already been requested."
          required: true
